### ISSUE TITLE
Video Mode Asynchronous inference

### ISSUE THREAD

**Issue by sngyo** [axinc-ai/ailia-models#115]
### 動画入力時に入出力処理および推論にかかった時間だけフレームを飛ばして次の推論を行うモードの実装希望

- webcameraモードだと`capture.frame`が呼び出されるタイミングごとに画像を撮ってくるので自動的に要件が満たされている．
- 動画を入力した場合
    - 現状: 全フレームを読み込んできて推論
    - 非同期モード: 実行時間を計測して，フレームあたりの単位時間でわって算出したフレーム数だけ飛ばして(?)から次の推論に入るようにすればよい？
        - ref: https://stackoverflow.com/questions/22704936/reading-every-nth-frame-from-videocapture-in-opencv

**Comment by prolleytroblems** [comment]
Assuming this is not for an image transformation process, but simply a labeling of some sort, have you thought about running the video stream on a separate thread? This way, the labels can be updated as they arrive from the model, rather than using a fixed frame skip. 

If, at the video startup, you add a delay between image capture and display equal to the expected runtime of the model, you could align the detections/classifications with their respective frames. If you add an additional 50% delay, you could swap the displayed predictions between the frames actually sent to the detector/classifier, minimizing the expected time gap between displayed frame and displayed prediction.

**Comment by kyakuno** [comment]
同期モードだけで問題ないと思うのでCloseします。
