### ISSUE TITLE
Facefusion: Add ability to list, sort and select face index.

### ISSUE THREAD

**Issue by ikmalsaid** [axinc-ai/ailia-models#1535]
Hi, I have used the Facefusion component and found it working very well. However, I would like to request the developers to improve Facefusion by adding abilities to list, sort and select face index (extremely useful if we want to swap an image with multiple faces).

Thank you!

**Comment by kyakuno** [comment]
@ikmalsaid Thank you for your request. If you try to give an ID to facefusion, I think tracking the person using features such as byte track is necessary. Since ailia-models provide minimal samples for the purpose of offering, there are no plans to add features, but it is possible to develop such functionality for your company through subcontracting.
