### ISSUE TITLE
ADD Age Transformation Using a Style-Based Regression Model

### ISSUE THREAD

**Issue by kyakuno** [axinc-ai/ailia-models#596]
https://github.com/yuval-alaluf/SAM
MIT

**Comment by kyakuno** [comment]
@sabosantech 弊社の方でrestyle_encoderのエクスポートに成功したため、同様の手順で、CUDAのコードをPythonのコードに置き換えればエクスポート可能になるのではと考えています。
https://github.com/axinc-ai/ailia-models/issues/478

下記のリポジトリ（ax社内公開）にアクセス権を追加しましたので、参考にしてみてください。
https://github.com/axinc-ai/restyle-encoder/compare/nathan/cuda2python

**Comment by Shysto** [comment]
@sabosantech @kyakuno I converted SAM into ONNX format.
You can find the models [here](https://drive.google.com/file/d/10b1klW1WfyovfmqwrolIRApCwZtq6DEl/view?usp=sharing) (need an ax account to see).

P.S.: Models larger than 2GB cannot be exported in one onnx file because of size limits imposed by Protocol Buffers.
The main onnx file can be found under `sam/sam.onnx`

**Comment by Shysto** [comment]
Because external data format is not supported by ailia yet, I cut the model in 3 sub-modules and exported each one to ONNX. I updated the models files given previously.

**Comment by Shysto** [comment]
@kyakuno The repo ailia can be found here: https://github.com/axinc-ai/ailia-models/tree/nathan/sam/generative_adversarial_networks/sam

Once the models uploaded, I will create a PR.

P.S.: to run without trouble, it needs the ailia release_1_2_9 + the minor code modification of psgan mentioned [here](https://github.com/axinc-ai/ailia-models/pull/626#discussion_r740692173)

**Comment by sabosantech** [comment]
@Shysto @kyakuno 
Thank you for sharing the way to convert SAM into ONNX.
I will try those tips next time.
